### ISSUE TITLE
Toolbar extension causes file upload modal to 'hang' when uploading files

### ISSUE THREAD

**Issue by tyssen** [mithra62/ee_debug_toolbar#53]
EE 2.8.1: when uploading a file via the file manager or via an entry, after having selected an image and clicking submit, the modal window goes grey and a spinning icon appears in the bottom right corner. The modal stays this way until you click close and refresh. 

The file does actually get uploaded, but the modal window doesn't refresh and continue to the point where you can edit/insert the image you've just uploaded.

Disabling the extension brings the functionality back.

**Comment by glawrie** [comment]
Might be worth checking to see if problem is to do with EEDT adding its debug code to end of the dialogue between browser and server during file transfer - I've got a similar problems with JSON files - if you are logged in and browser pulls JSON from template on EE system, EEDT inserts its HTML / CSS calls to the end of the message file, breaking the receiving process (which can't process the html tags).

Fix would be to modify EEDT to check that the template being called is intended to generate HTML perhaps.
