### ISSUE TITLE
PHP error on installation re cache_dir

### ISSUE THREAD

**Issue by jkorff** [mithra62/ee_debug_toolbar#56]
When I install the module I get the following PHP error message when accessing the Extensions screen in EE:

A PHP Error was encountered
Severity: Warning
Message: mkdir() [function.mkdir]: Permission denied
Filename: ee_debug_toolbar/ext.ee_debug_toolbar.php
Line Number: 130

That line is trying to create the cache directory:

			mkdir($this->cache_dir, 0777, true);

In my EE settings, I have set no cache path, i.e. the setting is empty. How can I avoid this error?

Thank you!

**Comment by jkorff** [comment]
Has no-one else come across this error?

**Comment by mithra62** [comment]
Sorry about that; this should be resolved in master now.
