### ISSUE TITLE
Upsets JSON data files... 

### ISSUE THREAD

**Issue by jcogs-design** [mithra62/ee_debug_toolbar#57]
Having a problem where EEDT is adding its access files to the end of a JSON file, and so breaking the page that loads the JSON file.

JSON is generated by an EE template (tagged as JSON in EE), and is called via an html call issued via a javascript ajax command.

The EE built-in debug code is aware of JSON files it seems - as it does not append itself to this file - but EEDT seems to insert its stuff regardless.

What is needed is for EEDT to check to see if template is generating HTML output I think.

I would have a go, but would be helpful to have a pointer or two as to where this test needs to go in add-on.  Or if it is easy to implement, perhaps someone can do the necessary...

**Comment by glawrie** [comment]
Partial fix - noticed that EEDT already disables itself for 'javascript', 'css', 'content_files_modal' templates - so simply redefined my JSON export as a javascript file and problem avoided, sort-of.
